export const Constants = {
    ADD_PRODUCT_REQ: 'ADD_PRODUCT_REQ',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    GET_PRODUCT_REQ: 'GET_PRODUCT_REQ',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAIL: 'GET_PRODUCT_FAIL',
    CHANGE_VIEW: 'CHANGE_VIEW'
}